[build]
  publish = "sr-token-wallet/dist/sr-token-wallet/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 