[build]
  base = "sr-token-wallet"
  publish = "dist/sr-token-wallet/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 